# Generated by Django 5.2 on 2025-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_problema', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
