# Generated by Django 5.2 on 2025-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0002_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('sector', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Sin asignar', max_length=30)),
            ],
        ),
    ]
