# Generated by Django 5.2 on 2025-05-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0003_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='App_LUMINOVA.producto'),
        ),
    ]
