# Generated by Django 5.2 on 2025-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0004_orden_cantidad_orden_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='producto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
